# Generated by Django 4.2.7 on 2023-11-06 06:42

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="stream",
            field=wagtail.fields.StreamField(
                [("richtext", wagtail.blocks.RichTextBlock())],
                blank=True,
                use_json_field=True,
            ),
        ),
    ]
